version: '2'

services:

    autoland.treestatus:
        image: mozilla/autolandtreestatus
        restart: always

    autoland.hg-init:
        image: mozilla/autolandhg
        command: init
        volumes:
            - autoland-hg:/repos

    autoland.hg:
        image: mozilla/autolandhg
        restart: always
        depends_on:
            - autoland.hg-init
        ports:
            - "${HOST_HGWEB}:${PORT}"
        volumes:
            - autoland-hg:/repos

    autoland.db:
        image: postgres:10.1-alpine
        restart: always
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASS}
        volumes:
            - autoland-db:/var/lib/postgresql

    autoland.transplant-init:
        image: mozilla/autolandtransplant
        command: init
        depends_on:
            - autoland.db
        volumes:
            - autoland-transplant:/repos
        links:
            - autoland.db:${DATABASE_HOST}

    autoland.transplant-api:
        image: mozilla/autolandtransplant
        restart: always
        command: api
        depends_on:
            - autoland.db
            - autoland.transplant-init
        ports:
            - "${HOST_AUTOLAND}:${PORT}"
        links:
            - autoland.db:${DATABASE_HOST}
            - autoland.hg:${REPO_HOST}

    autoland.transplant-daemon:
        image: mozilla/autolandtransplant
        restart: always
        command: daemon
        environment:
            TREESTATUS_URL: "http://treestatus:${PORT}/%s"
        depends_on:
            - autoland.db
            - autoland.transplant-init
        links:
            - autoland.db:${DATABASE_HOST}
            - autoland.hg:${REPO_HOST}
            - autoland.treestatus:treestatus

volumes:
    autoland-hg:
    autoland-db:
    autoland-transplant:
